---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: "12.3.0"
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: "2.2.0"
  - name: ansible.utils
    source: https://galaxy.ansible.com
    version: "6.0.1"
