---
# tasks file to configure ufw firewall
- name: Set logging
  become: true
  community.general.ufw:
    logging: 'on'
  tags:
    - ufw-log

- name: Reject instead of denied and log
  become: true
  community.general.ufw:
    rule: reject
    port: auth
    log: true
  tags:
    - ufw-log

- name: Allow outgoing
  become: true
  community.general.ufw:
    state: enabled
    direction: outgoing
    policy: allow
  tags:
    - ufw-allow

- name: Limit ssh connection
  become: true
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Deny incoming
  become: true
  community.general.ufw:
    state: enabled
    direction: in
    rule: deny
  tags:
    - ufw-deny

- name: Allow http/https tcp connection
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Allow dns port
  become: true
  community.general.ufw:
    rule: allow
    port: 53
    from_ip: "{{ item }}"
  loop:
    - 192.168.4.0/27
    - 10.10.2.2/29

- name: Allow Wireguard port
  become: true
  community.general.ufw:
    rule: allow
    port: 52001
    proto: udp


- name: Allow Home-assistant port
  become: true
  community.general.ufw:
    rule: allow
    port: 8225
    proto: tcp
