---
- name: First playbook
  hosts: all
  tasks:
    - name: Import updade role
      ansible.builtin.import_role:
        name: update
    - name: Import ufw role
      ansible.builtin.import_role:
        name: ufw
      when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - name: Import user role
      ansible.builtin.import_role:
        name: users
